version: '3.8'
services:
  db:
    image: postgres
    container_name: db_pizza
    command: -p 1225
    expose:
      - 1225
    env_file:
      - .env-non-dev
    
    
    restart: always
    
  app: 
    build: ./
    env_file:
      - .env-non-dev
    container_name: pizza_app
    ports:
      - 7775:8000
    depends_on:
      - db
    restart: always