version: '3.8'
services:
  db:
    image: postgres
    container_name: db_pizza
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    
    
    restart: always
    
  app: 
    build: .
    env_file:
      - .env-non-dev
    container_name: pizza_app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always